version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.3.1-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - train
      - run
      - --cors "*"
  app:
    image: rasa-actions-img
    expose: [5055]